### ISSUE TITLE
Cannot Change Listening Client Ports

### ISSUE THREAD

**Issue by JacobCarrell** [SolraBizna/onizd#2]
I'm trying to make this a docker image so I can deploy it on my infrastructure and offer free on demand hosting. However, that means running multiple servers from the same IP, and I see no way on the command line to specify listening port, timeout, or accepted inbound ports range. This may just be because I'm not familiar with Go,

**Comment by SolraBizna** [comment]
It's Rust, actually, not Go.

The Readme specifies how you can provide command line arguments by passing them after `--` when calling `cargo run`. Since you seem to be running this at a scale where `cargo run` is annoying, you can build an executable with:

```sh
cargo build --release
```

which will create an executable `target/release/onizd`, which you can copy somewhere else or use in-place without `cargo run`.

Either way, you can change the listening port and address with `-l` (lowercase L), for example:

```sh
# with cargo:
cargo run --release -- -l 0.0.0.0:7777
# with the executable:
onizd -l 0.0.0.0:7777
```

to listen on "any address" and port 7777.

Your project sounds exciting. Are there any features you'd like me to add to the server that would make it easier for you? Automatically terminating if no connections are active for a certain time period, perhaps? Also, I don't know if you saw, but on the `master` branch there's an experimental feature for saving map state between invocations; this may or may not be relevant to you as well.

**Comment by JacobCarrell** [comment]
I phrased it poorly. The initial communication port is indeed changable. But, the ports the client tries to connect over are not.
If I'm hosting multiple server instances behind a single IP, need to specify the ports that are forwarded to the application. Unless, I think, you implement NAT traversal. However, until then, being able to specify client port range will let me run multiple instances and control how many people can connect to a single instance

**Comment by SolraBizna** [comment]
I'm confused. The clients don't accept incoming connections, only the server does. The clients' outgoing ports are ephemeral, as is standard practice for TCP connections. NAT traversal isn't required for this situation.

**Comment by SolraBizna** [comment]
I'm closing this issue because I believe that the protocol's use of single, client-to-server TCP connections for all communications is fine for your project. Feel free to re-open if you think I'm in error.
